export { default as Home } from './Home/Home'
// export { default as About } from './About'
export { default as NotFound } from './NotFound'
export { default as Courses } from './Courses/Courses'
export { default as Life } from './Life/Life'
export { default as Reviews } from './Reviews'
export { default as ChatPage } from './ChatPage/ChatPage'
export { default as Canteen } from './Canteen'
export { default as ReviewInfo } from './ReviewInfo'
export { default as SchoolBus } from './SchoolBus'
export { default as Admin } from './Admin/Admin'
export { default as AdminUsers } from './Admin/AdminUsers'
export { default as AdminCourseComments } from './Admin/AdminCourseComments'
export { default as AdminCourses } from './Admin/AdminCourses'
export { default as AdminLocations } from './Admin/AdminLocations'
export { default as AdminDishs } from './Admin/AdminDishs'