# 通用默认配置：仅保留跨环境共享内容
spring:
  profiles:
    default: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  tomcat:
    max-swallow-size: -1

app:
  authentication: false
  swagger-enabled: true

logging:
  pattern:
    dateformat: mm:ss.SSS

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
