export { default as http } from './http'
export { homeApi } from './api'
export { getUserInfo , getUserInfoList , updateUserInfo} from './userInfo'
export { loginApi , registerApi } from './userApi'
export { getCourses , getUpdateCourses , updateCourse} from './courseApi'
export { chatApi } from './chatApi'
export { getCanteenLocations , getCanteenLocation , getDishList , getUpdateLocations,updateCanteenLocation } from './canteenLocationApi'
export { getDishes , getDish , getUpdateDishes , updateDish } from './dishApi'
export { getCourseCommmentsByCourseId , getCoursesCommmentList , getUpdateCoursesCommmentList , updateCourseComment , commitCourseComment} from './courseCommentApi'
export { xiaoY_chat , getList , getMessages , getNewMemoryId } from './ChatMessagesApi'
export { uploadAvatar } from './common'
export { fillClassApi } from './fillApi'
export { insertNamespace , deleteNamespace , insertRecord , deleteRecord , getNamespaces , getRecords , updateNamespace} from './vectorDbApi'