export { default as http } from './http'
export { homeApi } from './api'
export { getUserInfo , getUserInfoList , updateUserInfo} from './userInfo'
export { loginApi , registerApi } from './userApi'
export { getCourses , getUpdateCourses , updateCourse} from './courseApi'
export { chatApi } from './chatApi'
export { getCanteenLocations , getCanteenLocation , getDishList , getUpdateLocations,updateCanteenLocation } from './canteenLocationApi'
export { getDishes , getDish , getUpdateDishes , updateDish } from './dishApi'
export { getCourseCommmentsByCourseId , getCoursesCommmentList , getUpdateCoursesCommmentList , updateCourseComment} from './courseCommentApi'
export { xiaoY_chat , getList , getMessages } from './ChatMessagesApi'